# Conform to: https://wiki.parity.io/Substrate-Style-Guide
combine_control_expr = false
comment_width = 100
# error_on_line_overflow = true
# error_on_unformatted = true
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
hard_tabs = true
ignore = [
    "client/block-builder/src/lib.rs",
    "client/rpc/src/state/tests.rs",
]
match_block_trailing_comma = true
max_width = 100
merge_imports = true
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
trailing_semicolon = false
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
